api/urls.py
from django.conf.urls import url,include
from api import views

urlpatterns = [
    url(r'^asset/', views.Asset.as_view()),
]

autoserver/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from stark.service.stark import site
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include("api.urls")),
    url(r'^stark/', site.urls),
    url(r"^",include("web.urls",namespace="web"))
]

repository/models.py
from django.db import models


class BusinessUnit(models.Model):
	"""
	业务线
	"""
	name = models.CharField('业务线', max_length=64, unique=True)

	class Meta:
		verbose_name_plural = "业务线表"

	def __str__(self):
		return self.name


class IDC(models.Model):
	"""
	机房信息
	"""
	name = models.CharField('机房', max_length=32)
	floor = models.IntegerField('楼层', default=1)

	class Meta:
		verbose_name_plural = "机房表"

	def __str__(self):
		return self.name


class Server(models.Model):
	"""
	服务器信息 主机
	"""

	device_status_choices = (
		(1, '上架'),
		(2, '在线'),
		(3, '离线'),
		(4, '下架'),
	)
	device_status_id = models.IntegerField('设备状态', choices=device_status_choices, default=1)

	idc = models.ForeignKey('IDC', verbose_name='IDC机房', null=True, blank=True, on_delete=models.CASCADE)
	cabinet_num = models.CharField('机柜号', max_length=30, null=True, blank=True)
	cabinet_order = models.CharField('机柜中序号', max_length=30, null=True, blank=True)

	business_unit = models.ForeignKey('BusinessUnit', verbose_name='属于的业务线', null=True, blank=True,
									  on_delete=models.SET_NULL)

	# 基本信息 + 主板信息 + CPU信息
	hostname = models.CharField('主机名', max_length=128, unique=True)
	os_platform = models.CharField('系统', max_length=16, null=True, blank=True)
	os_version = models.CharField('系统版本', max_length=16, null=True, blank=True)

	sn = models.CharField('SN号', max_length=64, db_index=True)
	manufacturer = models.CharField(verbose_name='制造商', max_length=64, null=True, blank=True)
	model = models.CharField('型号', max_length=64, null=True, blank=True)

	cpu_count = models.IntegerField('CPU个数', null=True, blank=True)
	cpu_physical_count = models.IntegerField('CPU物理个数', null=True, blank=True)
	cpu_model = models.CharField('CPU型号', max_length=128, null=True, blank=True)

	latest_date = models.DateField('最后更新时间', null=True	)
	create_at = models.DateTimeField(auto_now_add=True, blank=True)

	class Meta:
		verbose_name_plural = "服务器表"

	def __str__(self):
		return self.hostname


class Disk(models.Model):
	"""
	硬盘信息
	"""
	slot = models.CharField('插槽位', max_length=8)
	model = models.CharField('磁盘型号', max_length=108)
	capacity = models.FloatField('磁盘容量GB')
	pd_type = models.CharField('磁盘类型', max_length=32)

	server = models.ForeignKey(verbose_name='服务器', to='Server', related_name='disk_list', on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = "硬盘表"

	def __str__(self):
		return self.slot


class NIC(models.Model):
	"""
	网卡信息
	"""
	name = models.CharField('网卡名称', max_length=128)
	hwaddr = models.CharField('网卡mac地址', max_length=64)
	netmask = models.CharField(max_length=64)
	ipaddrs = models.CharField('ip地址', max_length=256)
	up = models.BooleanField(default=False)
	server = models.ForeignKey('Server', related_name='nic_list', on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = "网卡表"

	def __str__(self):
		return self.name


class Memory(models.Model):
	"""
	内存信息
	"""
	slot = models.CharField('插槽位', max_length=32)
	manufacturer = models.CharField('制造商', max_length=32, null=True, blank=True)
	model = models.CharField('型号', max_length=64)
	capacity = models.FloatField('容量', null=True, blank=True)
	sn = models.CharField('内存SN号', max_length=64, null=True, blank=True)
	speed = models.CharField('速度', max_length=16, null=True, blank=True)

	server = models.ForeignKey('Server', related_name='memory_list', on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = "内存表"

	def __str__(self):
		return self.slot


class AssetRecord(models.Model):
	"""
	资产变更记录
	"""
	server = models.ForeignKey('Server', related_name='records_list', on_delete=models.CASCADE)
	content = models.TextField(null=True)
	create_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "资产记录表"
		# 排序，按照时间降序(括号内必须是一个元组或列表)
		ordering = ("-create_at",)

class ErrorLog(models.Model):
	"""
	错误日志,如：agent采集数据错误 或 运行错误
	"""
	server = models.ForeignKey('Server', null=True, blank=True, on_delete=models.CASCADE)
	title = models.CharField(max_length=16)
	content = models.TextField()
	create_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "错误日志表"

	def __str__(self):
		return self.title

web/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <h1>欢迎来到云顶之弈</h1>
{% endblock %}

web/templates/server_detail.html
{% extends 'layout.html' %}


{% block css %}

    <style>

        .guige {
            margin: 20px;
        }

        .guige-table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
        }

        .guige-table .title {
            background: #f5fafe;
            text-align: left;
            font-weight: bold;
            line-height: 32px;
            height: 32px;
            font-family: "微软雅黑";
        }

        .guige-table td, .content .guige-table th {
            border: 1px solid #dcdcdc;
            line-height: 30px;
            height: 30px;
            padding: 0 10px;
        }

        .guige-table .body-left {
            width: 126px;
            font-weight: normal;
            text-align: right;
            color: #666;
        }

        .guige-table .body-right {
            color: #333;
        }

    </style>

{% endblock %}


{% block content %}

    <div class="guige">
        <table class="guige-table">
            <tbody>
            <tr>
                <th colspan="5" class="title f14" style="border-left:2px solid #0488cd;">主机信息</th>
            </tr>
            <tr>
                <td colspan="2">主机名:{{ obj.hostname }}</td>
                <td colspan="1"><span style="color: rebeccapurple;">系统:{{ obj.os_platform }}</span></td>
                <td colspan="2">CPU个数:{{ obj.cpu_count }}</td>

            </tr>


{#            <tr>#}
{#                <td colspan="2">{{ obj.hostname }}</td>#}
{#                <td>{{ obj.os_platform }}</td>#}
{#                <td colspan="2">{{ obj.cpu_count }}</td>#}


{#            </tr>#}
            <tr>
                <td colspan="2.5"><span style="color: rebeccapurple;">CPU型号:</span> {{ obj.cpu_model }}</td>
                <td colspan="2.5">sn号: {{ obj.sn }}</td>

            </tr>
{#            <tr>#}
{#                <td colspan="2">{{ obj.cpu_model }}</td>#}
{#                <td colspan="3">{{ obj.sn }}</td>#}
{#            </tr>#}


            <tr>
                <th colspan="5" class="title f14" style="border-left:2px solid #0488cd;">网卡信息</th>
            </tr>
            <tr>
                <td>名称</td>
                <td>MAC地址</td>
                <td>IP地址</td>
                <td colspan="2">掩码</td>
            </tr>
{#    反向查询通过（网卡表中related_name='nic_list'） .all取网卡所有信息  #}
            {% for nic in obj.nic_list.all %}
                <tr>
                    <td>{{ nic.name }}</td>
                    <td>{{ nic.hwaddr }}</td>
                    <td>{{ nic.ipaddrs }}</td>
                    <td colspan="2">{{ nic.netmask }}</td>
                </tr>
            {% endfor %}



            <tr>
                <th colspan="5" class="title f14" style="border-left:2px solid #0488cd;">
                    <span>内存信息</span>

                </th>
            </tr>
            <tr>
                <td>插槽</td>
                <td>容量</td>
                <td>型号</td>
                <td colspan="2">制造商</td>
            </tr>

            {% for memory in obj.memory_list.all %}
                <tr>
                    <td>{{ memory.slot }}</td>
                    <td>{{ memory.capacity }}</td>
                    <td>{{ memory.model }}</td>
                    <td colspan="2">{{ memory.manufacturer }} </td>
                </tr>
            {% endfor %}



            <tr>
                <th colspan="5" class="title f14" style="border-left:2px solid #0488cd;">
                    <span>硬盘信息</span>
                </th>
            </tr>
            <tr>
                <td>插槽</td>
                <td>容量</td>
                <td>接口类型</td>
                <td colspan="2">型号</td>

            </tr>


            {% for disk in obj.disk_list.all %}
                <tr>
                    <td>{{ disk.slot }}</td>
                    <td>{{ disk.capacity }} GB</td>
                    <td>{{ disk.pd_type }}</td>
                    <td colspan="2">{{ disk.model }}</td>
                </tr>

            {% endfor %}


            </tbody>
        </table>
    </div>



{% endblock %}

web/templates/server_list.html
{% extends  'layout.html' %}
{% block content %}
    <table  class=" table  table-bordered table-hover">
    <thead>
    <tr>
            <th>序号</th>
            <th>主机名</th>
            <th>状态</th>
            <th>机房</th>
            <th>机柜号</th>
            <th>机柜中序号</th>
            <th>业务线</th>
            <th>变更记录</th>
            <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <a href="{% url "web:server_add" %}" class="btn btn-success btn-sm">新增</a>
    {% for foo in server %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td> <a href="{% url 'web:server_detail' foo.pk %}"> {{ foo.hostname }}</a></td>
        <td>{{ foo.get_device_status_id_display }}</td>
        <td>{{ foo.idc }}</td>
        <td>{{ foo.cabinet_num }}</td>
        <td>{{ foo.cabinet_order }}</td>
        <td>{{ foo.business_unit }}</td>
        <td> <a href="{% url 'web:server_record' foo.pk %}"> <i class="fa fa-outdent"></i></a></td>
        <td><a href="{% url "web:server_edit" foo.pk %}"><i style="position: absolute;margin: auto;" class="fa fa-edit"></i></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

web/templates/server_record.html
{% extends 'layout.html' %}


{% block css %}
    <style>

        .time {
            padding: 10px;
            border: 1px solid #ddd;
            position: absolute;
            width: 161px;
            left: -190px;
            box-shadow: 0 2px 8px 2px rgba(0, 0, 0, 0.12);
        }

        .record {
            padding: 10px;
            border: 1px solid #ddd;
            margin: 17px;
            min-height: 40px;
            box-shadow: 0 2px 8px 2px rgba(0, 0, 0, 0.12);
        }

        .record .auther {
            text-align: right;
            padding: 5px 0px;
            color: #9E9C9C;
        }

        .record-arrow {
            position: absolute;
            width: 24px;
            height: 14px;
            background: url(/static/img/bg_dot_left3.png) no-repeat;
            top: 15px;
            left: -6px;
            text-indent: -9999em;
        }

        .tag {
            padding: 6px;
            background-color: #00a2ca;
            margin: 10px;
            color: white;
            cursor: pointer;
            border-radius: 10px;
        }

        .add-tag {
            margin: 10px;
            color: #00a2ca;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
{% endblock %}

{% block content %}


    <div content="3" class="clearfix" style="margin-left: 190px">


        {% for record in obj.records_list.all %}
            <div class="left clearfix" style="border-left:2px dashed #ddd;">

                <div style="position:relative;">
                    <div class="time">{{ record.create_at|date:'Y-m-d H:i:s' }}</div>
                    <div class="record-arrow"></div>
                    <div class="record">
                        {{ record.content }}
                        <div class="auther">
                            <span><i class="fa fa-user"></i></span>
                            <span>cmdb</span>
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}


    </div>


{% endblock %}